resolver: lts-18.27
allow-newer: true

packages:
  - '.'

extra-deps:
- intern-0.9.2
- located-base-0.1.1.1
- text-format-0.3.2
- tasty-rerun-1.1.14
- rest-rewrite-0.3.0
- git: https://github.com/ucsd-progsys/liquid-fixpoint
  commit: a418d1039864f51c813622a6b0d7d658ff63fbcd
